# fly.toml file generated for madoka-senpai on 2023-05-17T11:18:51Z

app = "madoka-senpai"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[env]
 token = "NDc0ODYyNTA1MzY2MjU3NjY0.G5OxOT.7rJ_Td1ov7YoJQ2kZbfJ-pfZVopzEDTLX12zBo"
